# config.toml
title = "Sensor only network."

# data selection
template = "ws_corrected"
run = "3day"
data_folder = "outputs_13step"
warmup_days = 1
num_training_runs = 100
num_test_runs = 5


# optimizer definitions
[optimizer]
name="adadelta"
learning_rate=0.01


# training regimen
[training_parameters]
batch_size = 32
epochs = 320
# Suppress logging.
verbose = 2
validation_split = 0.2
shuffle = true


# network definition
[topology]
elements = [
  "33-488083.1", "36-486019.1", "33-486014.1", "33-478019.1", 
  "33-486037.1", "36-474088.1", "36-486015.1", "36-486016.1"
]
adjacency_matrix = [
  [1, 1, 0, 0, 0, 0, 1, 0],
  [1, 1, 1, 0, 0, 0, 1, 0],
  [0, 1, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 0, 0, 1],
  [0, 0, 0, 0, 1, 1, 1, 0],
  [0, 0, 0, 0, 1, 1, 0, 0],
  [1, 1, 0, 0, 1, 0, 1, 1],
  [0, 0, 0, 1, 0, 0, 1, 1]
]

# TODO: generate this from a `layers` definition and the `topology` info
[[network]]
name = "33-488083.1"
input_vars = ["33-488083.1", "36-486019.1", "36-486015.1", "rainfall"]
output_vars = ["33-488083.1_capacity_pred"]
layers = {type = "Dense", activation = "relu", units = [14, 7, 3, 1]}

#[[network]]
#name = "36-486019.1"
#input_vars = ["36-486019.1", "33-488083.1", "33-486014.1", "36-486015.1", "rainfall"]
#output_vars = ["36-486019.1_capacity_pred"]
#layers = {type = "Dense", activation = "relu", units = [17, 8, 4, 1]}

#[[network]]
#name = "33-486014.1"
#input_vars = ["33-486014.1", "36-486019.1", "rainfall"]
#output_vars = ["33-486014.1_capacity_pred"]
#layers = {type = "Dense", activation = "relu", units = [10, 5, 2, 1]}

#[[network]]
#name = "33-478019.1"
#input_vars = ["33-478019.1", "36-486016.1", "rainfall"]
#output_vars = ["33-478019.1_capacity_pred"]
#layers = {type = "Dense", activation = "relu", units = [10, 5, 2, 1]}

#[[network]]
#name = "33-486037.1"
#input_vars = ["33-486037.1", "36-474088.1", "36-486015.1", "rainfall"]
#output_vars = ["33-486037.1_capacity_pred"]
#layers = {type = "Dense", activation = "relu", units = [14, 7, 3, 1]}

#[[network]]
#name = "36-474088.1"
#input_vars = ["36-474088.1", "33-486037.1", "rainfall"]
#output_vars = ["36-474088.1_capacity_pred"]
#layers = {type = "Dense", activation = "relu", units = [10, 5, 2, 1]}

#[[network]]
#name = "36-486015.1"
#input_vars = ["36-486015.1", "33-488083.1", "36-486019.1", "36-486016.1", "33-486037.1", "rainfall"]
#output_vars = ["36-486015.1_capacity_pred"]
#layers = {type = "Dense", activation = "relu", units = [21, 10, 5, 1]}

#[[network]]
#name = "36-486016.1"
#input_vars = ["36-486016.1", "36-486015.1", "33-478019.1", "rainfall"]
#output_vars = ["36-486016.1_capacity_pred"]
#layers = {type = "Dense", activation = "relu", units = [14, 7, 3, 1]}



